version: '3'

services:
  web:
    image: gptmicroservice:v1
    container_name: chatgptmicroservice
    ports:
      - "8000:8000"
    volumes:
      - ./CsvData:/app/data
    environment:
      - OPENAI_API_KEY=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
    command: ["uvicorn", "querygpt4:app", "--host", "0.0.0.0", "--port", "8000"]

 