version: '3'

services:
  web:
    image: gpt:v1
    container_name: chatgptmicroservice
    ports:
      - "8000:8000"
    volumes:
      - ./CsvData:/app/data
    environment:
      - .env
    command: ["uvicorn", "querygpt4:app", "--host", "0.0.0.0", "--port", "8000"]

 